### ISSUE TITLE
Missing task for starting the server

### ISSUE THREAD

**Issue by nelsonmestevao** [filipecabaco/francis#5]
At the moment, you just run `mix run --no-halt` and you got yourself a server running. This is awesome because it is bult-in into mix itself. However, it does mean that by just `iex -S mix` into your application you get the server started. The real issue is that will prevent us from having multiple IEx sessions, since all will try to bind to the same TCP port.

We could provide a [Mix.Task](https://hexdocs.pm/mix/Mix.html#module-mix-task)  for this action, something like `mix francis.server` (similar to what [Phoenix](phoenixframework.org/) provides in here https://github.com/phoenixframework/phoenix/blob/main/lib/mix/tasks/phx.server.ex).

*This issue comes from [this ~~twitter~~X thread](https://twitter.com/nelsonmestevao/status/1701912734399385908).*

**Comment by filipecabaco** [comment]
Closed by https://github.com/filipecabaco/francis/pull/14
